server:
  port: 8002
spring:
  application:
    name: aigou-product
  datasource:  #数据库的配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou_product?useUnicode=true&characterEncoding=UTF-8  #防止中文乱码
    username: root
    password: 1234
mybatis-plus:
  mapper-locations: classpath:cn/ty/igou/mapper/*Mapper.xml #扫mapper映射
  type-aliases-package: cn.ty.igou.domain,cn.ty.igou.query  #别名的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
